<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class FarmerProfile extends Model
{
    use HasFactory;

    protected $fillable = [
            'name',
            'email',
            'data_collection_date',
            'location_address',
            'district',
            'sub_county',
            'parish',
            'village',
            'respondent_name',
            'respondent_gender',
            'respondent_dob',
            'is_respondent_owner',
            'dob_of_owner',
            'gender_of_owner',
            'marital_status_owner',
            'level_of_education_owner',
            'type_of_house_owner',
            'type_of_roofing',
            'religion_of_owner',
            'registered_phone_owner',
            'belongs_to_agricultural_group',
            'benefits_of_group',
            'is_group_for_poiltry_farmers',
            'when_started_egg_production',
            'type_of_birds_kept',
            'number_of_laying_birds',
            'main_source_of_feeds',
            'source_of_birds',
            'is_source_good',
            'source_of_birds2',
            'is_source_good2',
            'source_of_birds3',
            'is_source_good3',
            'how_many_annual_cycles',
            'what_records_kept_at_farm',
            'who_provides_labor',
            'frequency_of_labor',
            'who_provides_labor2',
            'frequency_of_labor2',
            'who_provides_labor2',
            'frequency_of_labor2',
            'major_challenges',
            'solution_to_challenge',
            'major_challenges2',
            'solution_to_challenge2',
            'major_challenges3',
            'solution_to_challenge3',
            'daily_trays_number',
            'weekly_trays_number',
            'minimum_price_in_area',
            'maximum_price_in_area',
            'current_egg_market',
            'Select_income_source',
            'do_you_get_money_from_source',
            'who_gets_it',
            'who_spends_it',
            'Select_income_source2',
            'do_you_get_money_from_source2',
            'who_gets_it2',
            'who_spends_it2',
            'Select_income_source3',
            'do_you_get_money_from_source3',
            'who_gets_it3',
            'who_spends_it3',
            'form_stage',
            'why_not_in_group',
            'marketing_information',
            'belongs_to_saving_group',
            'saving_group_name',
            'saving_group_type',
            'saving_group_name2',
            'saving_group_type2',
            'saving_group_name3',
            'saving_group_type3',
            'consultation',
            'consultation_number',
            'information_requested',
            'required_training',
            
    ];
    
}
